import type { Metadata } from "next";
import { Fraunces, Inter } from "next/font/google";
import "./globals.css";

// Product UI *and* product headings are both Inter now (spec §3). Inter is a
// real variable font, so one load covers 400 through 700 — `.font-display` in
// globals.css just asks for 600 and -0.02em tracking on top of the same file.
const sans = Inter({ subsets: ["latin"], variable: "--font-sans" });

// The marketing surfaces (`/`, `/login`, `/join`) keep one expressive face,
// and this is it. Note the variable: `--font-marketing`, NOT `--font-display`.
// Fraunces no longer drives product headings, and the SOFT/WONK axes that are
// the whole reason it loads as a variable font now apply through
// `.font-marketing` in globals.css, which is scoped to those routes.
const marketing = Fraunces({
  subsets: ["latin"],
  variable: "--font-marketing",
  style: ["normal", "italic"],
  axes: ["SOFT", "WONK"],
});

// Runs before first paint, so a dark-theme user never sees a light frame.
// Deliberately tiny and deliberately inline: a module in the bundle would be
// fetched after the first paint, which is the whole problem. No stored choice
// falls through to prefers-color-scheme — that is where "system" lives now
// that the toggle is one button instead of three.
const BOOT_THEME = `try{var t=localStorage.getItem("theme");if(t==="dark"||(!t&&matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.dataset.theme="dark"}catch(e){}`;

export const metadata: Metadata = {
  title: "Little Trips — plan cute little adventures together",
  description: "A shared trip-planning journal for you and the people you love.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // suppressHydrationWarning is load-bearing, not noise-suppression: the
    // script above stamps data-theme onto this exact element before React
    // hydrates, so React finds an attribute it did not render and warns. The
    // warning is correct and the situation is intended. It suppresses one
    // element's attribute diff, not its subtree's.
    //
    // --font-display is aliased to --font-sans rather than given its own
    // Inter() call: two calls would emit two <link rel=preload> for the same
    // woff2. One family, two roles, one download.
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sans.variable} ${marketing.variable}`}
      style={{ "--font-display": "var(--font-sans)" } as React.CSSProperties}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: BOOT_THEME }} />
      </head>
      <body className="font-sans">
        {/* Paper grain, not blurred orbs. The three `blur-3xl` circles that
            used to live here were the most recognizable "generated by a
            language model" default in the whole project — warm-toned, so they
            never read as purple, but still three shapes that meant nothing.
            The grain does the same job (depth behind the content) while
            actually saying what this app is: a page in a journal. Definition,
            and the contrast measurement that fixes its opacity, live in
            app/globals.css. */}
        <div aria-hidden className="pointer-events-none fixed inset-0 bg-paper" />
        <div className="relative">{children}</div>
      </body>
    </html>
  );
}
